### ISSUE TITLE
Query regarding MyIO package

### ISSUE THREAD

**Issue by ArihantKumarSeraogi** [wedusk101/NumericalAnalysis#2]
**Rohit how to integrate two different packages how to bundle them up**..will have to keep them in the same folder(how will the end user know this?) 
from where will he get the user defined MyIO package on his local machine Considering this methods will be totally ABSTRACT to the user oi tho sudhu ekta numerical package pabe oita import kore function call marbe ???

**Comment by ImRohitSingh** [comment]
We can add this package to the Java library! What Sir will exactly be doing while importing the Numerical package created by us! Else what's the point of creating the Numerical package?

**Comment by ArihantKumarSeraogi** [comment]
We can add how will the end user add .. where will he get the package MyIO

**Comment by ArihantKumarSeraogi** [comment]
the myIO package is on your local machine remember that  how will the user get it

**Comment by wedusk101** [comment]
> We can add this package to the Java library! What Sir will exactly be doing while importing the Numerical package created by us! Else what's the point of creating the Numerical package?

Rohit, the package is not for our use. Hence, there is no reason whatsoever why we should override a standard package in Java. And this is a package not a library. Integrating the MyIO package will create a number of problems for us:

1> We will need to document all the changes we have implemented by overriding the standard classes.

2>The user might still use the original methods thus rendering the MyIO package useless.

3>Overriding the standard classes will require us to be a lot more careful and we will need to strictly adhere to the original definitions to make sure we don't lose functionality.

4>We will need to perform even more extensive compliance testing before we finally push out the package.

5>Adding the MyIO package by archiving it with the Numerical Analysis package will violate the package classification hierarchy.

6>The list will go on...

**Comment by ImRohitSingh** [comment]
The reasons are absolutely absurd, from my point of view! Ultimately, the
codes are not to be sent! We will be sending ta jar file! So of we have a
way of reducing typing work and make the code more creative to learn the
subject, I see no reason why not to use that! For future use of this
package, the whole group cannot submit the same to wherever required. For
personal use we have to make necessary changes. Anyway, I will be changing
the codes and re write them by tonight!

**Comment by ImRohitSingh** [comment]
I have changed them.

**Comment by wedusk101** [comment]
Thank you. I'm marking this issue as closed for now.
