### ISSUE TITLE
Issues with the TrapezoidalRule.java prg 

### ISSUE THREAD

**Issue by Souvikpal000** [wedusk101/NumericalAnalysis#4]
this program is giving the following errors with this following input 
run:
Enter the highest degree of polynomial
1
Enter the coefficient
1
Enter the respective exponent
1
Exception in thread "main" java.lang.NullPointerException
	at TrapezoidalRule.f(TrapezoidalRule.java:33)
	at TrapezoidalRule.integrateTrapezoid(TrapezoidalRule.java:51)
	at TrapezoidalRule.main(TrapezoidalRule.java:71)
C:\Users\souvik\AppData\Local\NetBeans\Cache\8.1\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 7 seconds)

**Comment by wedusk101** [comment]
I have edited the lines where you were creating the array of coefficients and the array of exponents in the constructor. The NullPointerExceptions are gone but the program is getting stuck on an infinite loop right now. Also on an unrelated, much less important issue, I suggest designing a separate driver class for the code.
